{/*const About =()=>{
    return(
        <div>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget ex ut dui tempus faucibus. Phasellus lorem orci, dapibus eget mauris in, elementum scelerisque est. Vivamus sed metus nec libero elementum feugiat a in enim. Duis eget erat euismod, semper nunc vel, tempus dui. Cras facilisis et velit non imperdiet. Sed vulputate dapibus nisl et sodales. Etiam a consectetur risus. Pellentesque interdum urna quis consectetur consequat. Nunc congue tempor neque, eu posuere est rutrum ut. Phasellus enim lacus, luctus nec leo eget, venenatis faucibus mauris. Proin a convallis orci. Sed tincidunt scelerisque ullamcorper. Quisque dictum tortor ac lacus finibus aliquam. Sed diam mi, imperdiet id ultricies et, egestas nec urna.

Nullam nec ultricies mauris, sit amet auctor ligula. In eu nulla elementum, feugiat elit at, ultrices dui. Curabitur eu sem felis. Sed sit amet nunc nunc. Cras sed euismod justo. Nam vel posuere felis. Maecenas erat massa, dictum vitae condimentum eget, sagittis rhoncus libero. Maecenas at laoreet nunc. In tincidunt diam eget nulla semper rhoncus.

Etiam molestie fringilla tortor eget malesuada. Nulla congue ligula diam. Maecenas bibendum velit sed volutpat pulvinar. Pellentesque tempus, lorem quis vulputate consectetur, dui massa rutrum lacus, ac hendrerit purus neque vitae metus. Fusce elit orci, accumsan sit amet tempor eu, aliquam nec dui. Nunc quis mattis magna, quis porta neque. Phasellus mollis ex et risus volutpat malesuada. Aenean fringilla dui eget tincidunt volutpat. Morbi at efficitur urna. Cras vel ante tincidunt, mollis nunc sagittis, condimentum felis. Sed in quam vel nulla lobortis consequat. Phasellus malesuada vestibulum nibh, in suscipit enim venenatis sed.

Nam malesuada lacinia nulla, sed facilisis velit ultricies id. Quisque vehicula enim quis varius placerat. Nulla eget ex non orci ullamcorper suscipit ut sit amet magna. Pellentesque aliquet, diam quis luctus blandit, sapien diam condimentum sapien, ut molestie nulla lacus et ex. Phasellus eleifend orci quis purus malesuada varius. Aliquam a nibh purus. Ut enim diam, dapibus at aliquet at, lobortis ut neque. Fusce consequat, enim ac vehicula laoreet, magna est fringilla ligula, non vehicula nisl ipsum volutpat justo.

Proin egestas felis eget magna sodales scelerisque. Morbi facilisis posuere felis, sit amet gravida justo interdum id. Pellentesque condimentum posuere nunc, quis hendrerit metus cursus id. Nunc eget consectetur ex. Sed egestas eleifend velit, sed commodo magna dictum ut. Quisque scelerisque ultrices metus, et pharetra mi. Integer sodales odio sed imperdiet sollicitudin. Quisque bibendum cursus consequat. In gravida urna ut porta maximus. Aliquam mollis lacinia volutpat. Sed velit tellus, feugiat vitae euismod sit amet, aliquam vitae nibh. Proin convallis, dolor sit amet euismod aliquam, libero elit malesuada ex, in iaculis elit neque at sapien. Phasellus id eros nibh.

Pellentesque vitae elit sed enim porttitor porta. Curabitur venenatis metus quam, vitae vulputate enim sodales sit amet. Ut tincidunt lacus ex, vel fermentum erat elementum nec. Sed aliquam congue nulla id imperdiet. Pellentesque gravida, leo eu porta facilisis, ante orci rhoncus odio, id consectetur massa libero ultrices ipsum. Ut id vulputate risus, eget vestibulum risus. Etiam hendrerit lorem at arcu sodales, vel rhoncus felis blandit. Curabitur leo nisl, convallis ut rhoncus venenatis, viverra tincidunt libero. Maecenas molestie justo vel tincidunt sollicitudin.

Quisque bibendum efficitur odio, at pretium ante luctus condimentum. Fusce dignissim massa vitae enim ullamcorper ultrices. Ut commodo tortor ligula, et rhoncus odio pharetra sit amet. Etiam suscipit nunc sit amet tempus facilisis. Proin posuere enim et urna blandit vulputate. Sed tempor ex et quam venenatis iaculis. Duis porta orci efficitur purus vestibulum, vel dictum ipsum rutrum. Duis nec lorem felis. Proin sit amet tortor condimentum, sagittis dolor quis, luctus nisi. Fusce iaculis elit risus, non viverra dui vulputate id. Sed eu justo tempus, pulvinar nulla vitae, viverra odio. Ut eleifend rutrum nisl vel porta. Praesent vestibulum rutrum risus vitae dignissim. Proin vitae velit cursus erat elementum lobortis.

Donec at pellentesque dui. Nullam dictum odio eget ligula cursus, et vehicula est mollis. Duis iaculis vulputate aliquam. Vestibulum dolor purus, tempus vel justo vel, laoreet iaculis est. Aliquam facilisis aliquet lacus, tincidunt bibendum nisl blandit quis. Aenean mauris ipsum, convallis vel ullamcorper volutpat, aliquam a lorem. Cras a nisl eu tortor interdum fermentum. Quisque in rhoncus lectus. Integer eget ante varius, ornare purus eget, rutrum odio. Cras sed sagittis massa.

Phasellus molestie ex dui, et rutrum elit rhoncus non. Donec vitae pretium velit. Sed ut nisi non tortor volutpat sodales sed non nulla. Nunc pharetra aliquet lorem, vestibulum eleifend ante luctus eget. Etiam mi mauris, sollicitudin vitae lacus non, dapibus malesuada quam. In hac habitasse platea dictumst. Nullam pharetra leo eget lacus volutpat viverra. Curabitur eget egestas diam. Nunc euismod massa et mi placerat mollis. Sed ac ipsum blandit, porta odio vitae, blandit odio. In bibendum cursus nibh, porttitor blandit sem porttitor tempus. Proin at magna risus. Pellentesque pulvinar, ante eget porttitor eleifend, metus eros aliquam nisl, eu blandit ex ligula vel eros. Proin massa mauris, congue sit amet massa in, volutpat pellentesque sem.

Suspendisse id magna diam. Phasellus rutrum pulvinar elit, sed vulputate metus efficitur a. Aenean bibendum justo ut leo dictum, vitae dictum lacus varius. Pellentesque ac vestibulum arcu. Quisque ac quam nec metus dictum lobortis. Curabitur gravida sodales risus, eget porta metus congue sit amet. Aenean pulvinar pretium libero, nec tempus sapien elementum vitae. Pellentesque eu hendrerit diam. In nec sagittis massa. Proin gravida gravida eleifend. Nam in consectetur sapien.

Sed eget viverra augue. Cras nec enim vel ligula efficitur imperdiet. Fusce in tincidunt ipsum. Pellentesque consectetur elementum bibendum. Quisque sed nulla felis. Sed porttitor efficitur metus, non dapibus risus cursus in. Ut volutpat viverra nisi eu vulputate. Vestibulum et condimentum diam. Vivamus feugiat ornare maximus.

Cras porttitor ipsum et maximus ultrices. Duis viverra elementum justo porta malesuada. Aliquam malesuada ante vel augue rutrum porttitor. Nunc quis lorem porttitor, laoreet tellus in, vestibulum tellus. Proin lobortis ut nunc sed fermentum. Duis vitae ex quis sem efficitur cursus. Curabitur maximus odio eget dignissim sodales. Phasellus luctus porttitor leo, imperdiet consequat neque. Donec tristique sapien non augue porttitor facilisis. In sit amet tellus sit amet nisl posuere consequat nec nec lacus. Quisque sed pharetra mi. Vivamus accumsan sollicitudin dui. Aenean et elementum leo. Integer ut neque faucibus, lobortis lacus at, pretium sem. Donec ac cursus sapien, vel blandit justo.

Vestibulum molestie convallis odio in tincidunt. Maecenas ornare velit at pellentesque suscipit. Integer viverra metus sed mauris vehicula dictum. Phasellus non sem eget ex bibendum pretium sed ut justo. Suspendisse id velit non lorem varius consectetur et at nisi. Suspendisse in rhoncus risus. In hac habitasse platea dictumst. Vivamus ipsum odio, porttitor sed nisi ut, rutrum pretium tellus. Donec vitae sagittis arcu. Curabitur mauris nulla, porta sed ullamcorper eget, malesuada eu urna. Aenean sed arcu sodales, semper nulla nec, mollis nisi. Curabitur id magna non eros interdum convallis. Donec sit amet nisl non nunc posuere euismod nec vitae risus. Curabitur quam sem, efficitur eu luctus a, aliquet eu ex. Mauris pellentesque, risus sit amet euismod porta, mauris arcu cursus lorem, quis iaculis nulla ipsum id est.

Pellentesque interdum tortor id felis lacinia, sed ultrices massa dignissim. Fusce euismod lacinia pharetra. Pellentesque a cursus leo. Nam congue, tortor vitae eleifend tempus, purus ligula luctus purus, at bibendum elit purus quis purus. Suspendisse dignissim leo cursus nibh ullamcorper aliquet. Sed mollis elementum justo, sit amet porttitor justo bibendum ut. Nam volutpat mi ac nisi maximus elementum. Pellentesque pellentesque lorem in lacus tincidunt, sit amet lobortis velit porttitor. Pellentesque elit metus, eleifend quis luctus et, aliquam sed est. Suspendisse sodales lobortis nisl, ac tincidunt mi mollis eget. Donec vel augue eget arcu efficitur condimentum. Morbi et lorem ipsum. Suspendisse iaculis felis nisl. Vestibulum id auctor lacus. Aenean dignissim iaculis nibh ultrices vestibulum. Cras malesuada vitae eros sed lacinia.

Duis mattis, diam vitae vulputate dignissim, dui arcu pharetra ante, quis sodales purus turpis quis erat. Donec eu dolor metus. Suspendisse potenti. Phasellus maximus tempor orci, eget laoreet eros viverra ornare. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis pharetra dolor justo, vitae bibendum odio lacinia non. Mauris eleifend ultricies justo, in egestas sapien lobortis vitae.

Phasellus vitae porttitor odio, sed vulputate odio. In eleifend mauris ut tincidunt finibus. Nunc tincidunt lacinia cursus. Nulla elit tellus, aliquam in justo sit amet, posuere blandit metus. Nulla auctor vehicula leo pretium lacinia. Vivamus non elit magna. Etiam massa augue, congue pulvinar lacus in, pretium faucibus elit. Sed blandit risus non ligula sagittis imperdiet. Morbi sed fringilla nisl. Sed purus nisi, laoreet ut sapien quis, pretium mattis dui. Curabitur in ligula a odio aliquam elementum. Vivamus vel orci in lacus tempus tempor quis ut eros. Mauris elit odio, viverra sit amet vestibulum non, hendrerit nec neque.

Mauris rhoncus, urna in consequat hendrerit, massa tellus volutpat massa, vel volutpat leo nunc eu sem. Vestibulum tristique laoreet iaculis. Fusce vel pulvinar odio, ac suscipit velit. Vestibulum quis posuere dolor. Nam molestie eros sed cursus efficitur. Suspendisse hendrerit arcu eget egestas tincidunt. Vivamus pretium cursus dolor nec aliquam. Aenean lacus dolor, faucibus ut cursus eu, aliquam nec mi.

Cras nisl mauris, suscipit sit amet vestibulum id, convallis eget mi. Proin fringilla maximus lorem. Fusce sollicitudin tortor at nisi molestie fringilla. Nullam in ex vel libero rutrum egestas quis sit amet elit. Pellentesque pretium vulputate odio quis fermentum. Suspendisse potenti. Praesent at justo vitae mi gravida tincidunt. Morbi semper tellus eget accumsan tincidunt. Aenean placerat vel metus nec sodales. Nullam fermentum at eros at malesuada. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum at lorem sed metus porta fringilla in sed ipsum. Donec elit risus, mollis eu congue ut, sodales et felis. Curabitur eu sapien molestie, ultrices metus eu, dignissim dolor.

Nunc auctor porta erat, sed semper diam scelerisque et. Praesent nec tristique neque, et aliquam mauris. Proin ut semper tortor. Duis vehicula, magna id consectetur consectetur, felis libero iaculis mauris, at ultricies est eros et tellus. Praesent porttitor, mi eget ornare suscipit, leo leo viverra sapien, vitae sodales augue eros at sem. Donec ut tortor eu nulla ultricies interdum. Nam velit tellus, finibus quis malesuada et, interdum nec dolor. Suspendisse porttitor lorem arcu, eget consequat tortor iaculis viverra. Pellentesque mollis odio libero, in scelerisque lorem malesuada at. Nam at leo sed justo finibus convallis. In semper vehicula augue, euismod ultricies nulla vehicula id. Curabitur eget porta leo, vel mollis dui. Cras ultricies nibh sit amet urna feugiat tempus. Nam placerat volutpat viverra. Phasellus lobortis eleifend leo, bibendum dapibus ante elementum sit amet.

Aenean vehicula augue ut dolor convallis, ac ultricies turpis sagittis. Praesent lacinia cursus dapibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper metus quis enim tincidunt imperdiet. Cras nec quam pharetra, laoreet nisi et, luctus dui. Curabitur placerat felis nibh, ut finibus justo laoreet nec. Etiam sit amet nulla turpis. In quis ultrices lectus. Nullam tempor tempus condimentum. Nullam non ullamcorper purus. Morbi hendrerit rutrum aliquet. Maecenas congue eleifend diam, in feugiat felis. Aenean at velit at arcu ultricies interdum sed in sem. Aenean vitae nibh cursus, tempor quam eu, congue nisi. Praesent ac augue in metus auctor dignissim sit amet luctus libero.
        </div>
    )
}

export default About ;
*/}